<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Task Completed</title>
</head>

<body style="margin:0; padding:0; font-family: Arial, sans-serif; background-color:#f5f5f5;">
    <div
        style="max-width: 600px; margin: 20px auto; background-color: #ffffff; border: 1px solid #dddddd; border-radius: 5px; overflow: hidden;">
        <div
            style="background-color: #4CAF50; color: white; padding: 20px; text-align: center; font-size: 24px; font-weight: bold;">
            Task Completed
        </div>
        <div style="padding: 20px; font-size: 16px; color: #333;">
            <p>The following task has been successfully completed:</p>
            <div
                style="margin-top: 10px; padding: 10px; background-color: #dff0d8; color: #3c763d; border: 1px solid #d6e9c6; border-radius: 4px;">
                Task Complete
            </div>
        </div>
        <div style="padding: 15px 20px; font-size: 13px; color: #777; background-color: #f9f9f9; text-align: center;">
            This notification was generated by the Task Manager System. Please log in to view full task details or
            perform further actions.
        </div>
    </div>
</body>

</html>
